# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  desafioUnicad-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: desafioUnicad-mysql
    volumes:
      - desafioUnicad-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=A123456
      - MYSQL_DATABASE=desafioUnicad
      - MYSQL_USER=root
      - MYSQL_PASSWORD=A123456

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: desafioUnicad-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql